[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "${MONAD_TESTNET_RPC_URL}"

[etherscan]
monad_testnet = { key = "${MONADSCAN_API_KEY}", url = "${MONADSCAN_API_URL}" }
